config/routes.rb
Rails.application.routes.draw do
  devise_for :userdevises
  # delete "/userdevise/sign_out", to: "devise/sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
  resources :users, only: [:new, :create]
  get "users/login", to: "users#login"
  post "users/login", to: "users#authenticate"
  delete "sign_out", to: "sessions#destroy"
  resources :products

  resources :alluserlists
  resources :product_carts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :product_carts
  has_many :userdevises, through: :product_carts
end

app/models/product_cart.rb
class ProductCart < ApplicationRecord
  belongs_to :userdevise
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, uniqueness: true, on: [:create, :update], presence: true
  validates :password, :password_confirmation, presence: true, length: { minimum: 6 }
  validates_confirmation_of :password
end

app/models/user_cart_item.rb
class UserCartItem < ApplicationRecord
  belongs_to :userdevise
  belongs_to :product
end

app/models/userdevise.rb
class Userdevise < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :product_carts
  has_many :products, through: :product_carts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/Item/electronics_controller.rb
class Item::ElectronicsController < ApplicationController
  def index
    @electronics = Product.all
  end

  def new
    @electronics = Product.new
  end

  def create
    @electronics = Product.create(electronics_params)

    if @electronics.save
      redirect_to root_url
    else
      render :new
    end
  end

  private

  def electronics_params
    params.require(:product).permit(:name, :price, :description, :category)
  end
end

app/controllers/alluserlists_controller.rb
class AlluserlistsController < ApplicationController
  def index
    @userlist = Userdevise.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  # helper_method :current_userdevise

end

app/controllers/product_carts_controller.rb
class ProductCartsController < ApplicationController
  def create
    # product = Product.find(params[:product_id])
    cart_item = current_userdevise.product_carts.find_by(product_id: params[:product_id])
    if cart_item
      cart_item.update(quantity: cart_item.quantity + 1)
    else
      current_userdevise.product_carts.create(product_id: params[:product_id], quantity: 1)
    end
    redirect_to root_path
  end

  def index
    # product_cart = ProductCart.includes(:product)
    # product_cart = current_userdevise
    @product_cart = current_userdevise.product_carts
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @product = Product.where(isdeleted: false)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find_by(id: params[:id])
  end

  def update
    @product = Product.find_by(id: params[:id])

    if @product.update(product_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find_by(id: params[:id])
    @product.update(isdeleted: true)
    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :description, :category, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/userdevise/sessions_controller.rb
# frozen_string_literal: true

class Userdevise::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/userdevise/unlocks_controller.rb
# frozen_string_literal: true

class Userdevise::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render :new
    end
  end

  def login
  end

  def authenticate
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_url, notice: "You are now logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render :login
    end
  end

  def show
  end

  def destroy
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/alluserlists_helper.rb
module AlluserlistsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/product_carts_helper.rb
module ProductCartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/product_carts/index.html.erb
<h1>Your Cart</h1>
<h1>User Email: <%= current_userdevise.email%></h1>
<table>
  <% if @product_cart.present? %>
    <thead>
      <tr>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      <% @product_cart.each do |product_cart| %>
        <tr>
          <td><%= product_cart.product.name %></td>
          <td><%= product_cart.product.price %></td>
          <td><%= product_cart.quantity %></td>
          <td><%= product_cart.quantity * product_cart.product.price%></td>
        </tr>
      </tbody>
    <% end %>
  <% else %>
    <p>Your cart is empty.</p>
  <%end%>
</table>
<%# 
<tr>
  <td colspan="3" class="text-end"><strong>Total</strong></td>
  <%# <td><%= @product_cart.sum { |product_cart| product_cart.product.price } %></td>
<%# </tr> %>

app/views/products/_form.html.erb
<%= form_with model: @product, local: true, html: { class: "form" } do |form| %>
  <%# <%= form.text_field :first_name, placeholder: "First name", required: true, class: "input" %>
  <%# <%= form.text_field :last_name, placeholder: "Last name", required: true, class: "input" %>
  <%= form.text_field :name, placeholder: "Product Name", required: true, class: "input" %>
  <%= form.text_field :price, placeholder: "Price", required: true, class: "input" %>
  <%= form.text_field :description, placeholder: "Product description", required: true, class: "input" %>
  <%= form.file_field :image, placeholder: "Product Image", required: true, class: "input"%>
  <%= form.select :category, options_for_select(["Electronics", "Cloths", "Grocery"]), { prompt: "Select a category" }, class: "input" %>
  <%= form.submit "Create Product", class: "button" %><br>
<% end %>

app/views/products/edit.html.erb
<center>
  <h1>Update an Product</h1>
</center>
<%= render 'form' %>

app/views/products/index.html.erb
<center>
  <h1>Product List</h1>
</center>
<div class="topbar">
  <ul>
  </ul>
</div>
<% if userdevise_signed_in? %>
  <td>Your Email: <%= current_userdevise.email%></td>
  <h2><%= link_to "Signout",destroy_userdevise_session_path, method: :delete %></h2>
  <%if current_userdevise.isadmin == false %>
    <h2>
      <td><%= link_to 'Show cart',product_carts_path%></td>
    </h2>
  <%else%>
    <h2>
      <td><%= link_to 'Add New Product',new_product_path%></td>
      <td><%= link_to 'SHow Users', alluserlists_path%>
      </h2>
    <%end%>
  <% else %>
    <h2><%= link_to "SignIn",new_userdevise_session_path%></h2>
  <% end %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Category</th>
        <th>Image</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @product.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= product.price %></td>
          <td><%= product.category %></td>
          <td><%if product.image.attached?%>
              <%= image_tag product.image, style: "width:120px;height:100px;"%>
            <%end%>
          </td>
          <% if current_userdevise && current_userdevise.isadmin %>
            <td><%= link_to 'Edit', edit_product_path(product)%></td>
            <td><%= link_to "Delete",product_path(product), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></td>
          <%else%>
            <td><%= form_tag product_carts_path do %>
                <%= hidden_field_tag :product_id, product.id%>
                <%= submit_tag "Add to Cart" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end%>
    </tbody>
  </table>

app/views/products/new.html.erb
<center>
  <h1>Create an Product</h1>
</center>
<%= render 'form' %>

app/views/users/login.html.erb
<center>
  <h1>Login Page</h1>
</center>
<%= form_with url: users_login_path, html: { class: "form" }, method: :post do |form| %>
  <%= form.email_field :email, placeholder: "Email address", required: true, class: "input" %>
  <%= form.password_field :password, placeholder: "Password", required: true, class: "input" %>
  <%= form.submit "Login", class: "button" %><br>
  <%=  link_to "You Dont't Have Account ?", new_user_path %>
<% end %>

app/views/users/new.html.erb
<center>
  <h1>Create an account</h1>
</center>
<%= form_with model: @user, local: true, html: { class: "form" } do |form| %>
  <%# <%= form.text_field :first_name, placeholder: "First name", required: true, class: "input" %>
  <%# <%= form.text_field :last_name, placeholder: "Last name", required: true, class: "input" %>
  <%= form.email_field :email, placeholder: "Email address", required: true, class: "input" %>
  <%= form.password_field :password, placeholder: "Password", required: true, class: "input" %>
  <%= form.password_field :password_confirmation, placeholder: "Confirm password", required: true, class: "input" %>
  <div class="field_with_errors">
    <%= @user.errors[:password_confirmation].join(", ") %>
  </div>
  <%= form.submit "Create account", class: "button" %><br>
  <%=  link_to "You Already Have An Account ?", users_login_path %>
<% end %>